name: about
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
dev_dependencies:
  core:
    path: ../core
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg